apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: mysecret
spec:
  encryptedData:
    foo: AgCYk+Y4oOd5RLV9CgbW2byt78//EU6Kygoy8A2hDy9HhnyEDhD4G3zy6Q/8kIEOhKO4BpVmgz7ccAyLDccDBLK/ZPCi4wqt6SxLK4sIoFpOOtZYi89H2phqJpsphJlR+vJN2V+9ARKP16gzfEDVwmBkXt5d7rg2kXZxl1FwqiFEBmy+J32pRzsqEvq24dOwue77SoH5hhVcVloX5vQCiWix85dIHHor6muPJqyms4CQ51ic2EweVAuqeaazFRhKZDd0HvqjJrrYNQTo4RzapfvQ0XZr4UxrbXJ7vZuRhBQpeUksdnux7bJ1mfXiO8vp4Djuo2e7pqtQ8q4rrwoE7gWOoMbIXCCiS3tw95CO7G2lpEmewRU62pJVHqhnFJKQH6lniiqWtuc2edvV0CTEW3nWKyqtGwPPLpZOuuBC0t+FQZlL1ReGouhLo1+RuCcmze4iGucfhEBvEVcxHjVuwBLje3B6oVDaB+LulbbIs8pXFVVoLpB6fbxierxzUCH+QPvqlkBRznUKaJZntnjG5Z1jd2g16gtdokanAyr7j91MLN9Rw9VZx6HRa6aGvGMyJQnQTLE+TGmawbDd3odneSLNnTPtNEx5vZdGCTRIApRdGID+SP6Ii6ax2k9sliX4WdsbUqwZ0GNqyEGhexErDhB7kRbU7HOtJlgCAEIpzq82A0koimQt/rC80xrbad17rQ1sa0s=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: mysecret
