apiVersion: batch/v1
kind: Job
metadata:
  generateName: hook-
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    metadata:
      name: long-task
    spec:
      containers:
      - name: long-task
        image: docker/whalesay
        command: ["cowsay", "Hello Kube"]
      restartPolicy: OnFailure
    
