apiVersion: batch/v1
kind: Job
metadata:
  name: hook-task
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    metadata:
      name: hook-task
    spec:
      containers:
      - name: long-task
        image: docker/whalesay
        command: ["cowsay", "Hello Kube"]
      restartPolicy: OnFailure
    
